package io.openems.edge.battery.sensatabms;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.common.startstop.StartStopConfig;

@ObjectClassDefinition(//
		name = "BMS sensata", //
		description = "Implementation for sensata BMS. Caution: OpenEMS communicates with the BMS using a CAN-Modbus bridge, which must be configured properly.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "sensatabms0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Start/stop behaviour?", description = "Should this Component be forced to start or stop?")
	StartStopConfig startStop() default StartStopConfig.START;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id() default "modbus0";
	
	@AttributeDefinition(name = "ESS-ID", description = "ID of ESS for Charge/Discharge command.")
	String ess_id() default "ess0";

	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device.")
	int modbusUnitId() default 1;

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";
	
	@AttributeDefinition(name = "Enable Blancing", description = "Is Balancing enabled?")
	boolean enable_balancing() default false;
	
	String webconsole_configurationFactory_nameHint() default "BMS Sensata [{id}]";

}